### PR TITLE
Re-enable `spotbugs` and fix some issues

### LINKED ISSUE #208: EOL `commonLibCLPaths`
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Winstone 5.22
Jenkins 2.334
Ubuntu 20.04.3 LTS x86_64

### Reproduction steps

Run `git grep -i commonLibCLPaths`.

### Expected Results

The search returns zero results.

### Actual Results

The search returns a nonzero number of results.

### Anything else?

I could find no references to `commonLibCLPaths` [anywhere in the Jenkins ecosystem](https://github.com/search?type=Code&q=user%3Ajenkinsci+commonLibCLPaths%60). In this repository, we populate `commonLibCLPaths` without ever consuming it, so it is dead code. There are no usages `HostConfiguration` or `HostGroup` outside of this repository, either. This dead code seems best left in the rear-view mirror. My suggestion is to remove all references to `commonLibCLPaths` from this repository.

### LINKED ISSUE #209: `winstone.realm.FileRealm` subject to XML external entity injection (XXE)
### Jenkins and plugins versions report

Winstone 5.23
Jenkins 2.334

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.3 LTS x86_64

### Reproduction steps

Create a `users.xml` with, say

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lolz [
 <!ENTITY lol "lol">
 <!ELEMENT lolz (#PCDATA)>
 <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
 <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
 <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
 <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
 <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
 <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
 <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
 <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
 <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
]>
<users>
  <role rolename="admin-gui"/>
  <role rolename="admin-script"/>
  <role rolename="manager-gui"/>
  <role rolename="manager-status"/>
  <role rolename="manager-script"/>
  <role rolename="manager-jmx"/>
  <user name="admin" password="admin" roles="admin-gui,admin-script,manager-gui,manager-status,manager-script,manager-jmx"/>
  <lolz>&lol9;</lolz>
</users>
```

then run Jenkins with `java -jar jenkins.war --realmClassName=winstone.realm.FileRealm --fileRealm.configFile=users.xml`.

### Expected Results

Jenkins should not attempt to process the XML external entities, failing to start with an error like the following:

```
$ java -jar jenkins.war --realmClassName=winstone.realm.FileRealm --fileRealm.configFile=users.xml
[…]
[Fatal Error] :2:10: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
2022-02-10 16:58:33.428+0000 [id=1]     INFO    winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to setup authentication realm
        at winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        at winstone.HostGroup.initHost(HostGroup.java:66)
        at winstone.HostGroup.<init>(HostGroup.java:45)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:376)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:304)
        at Main.main(Main.java:108)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:69)
        ... 10 more
Caused by: winstone.WinstoneException: Error parsing the users XML document
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:128)
        at winstone.realm.FileRealm.<init>(FileRealm.java:59)
        ... 15 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:125)
        ... 16 more
2022-02-10 16:58:33.429+0000 [id=1]     SEVERE  winstone.Logger#logInternal: Container startup failed
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:125)
Caused: winstone.WinstoneException: Error parsing the users XML document
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:128)
        at winstone.realm.FileRealm.<init>(FileRealm.java:59)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:69)
Caused: java.io.IOException: Failed to setup authentication realm
        at winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        at winstone.HostGroup.initHost(HostGroup.java:66)
        at winstone.HostGroup.<init>(HostGroup.java:45)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:376)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:304)
        at Main.main(Main.java:108)
```

### Actual Results

Jenkins attempts to process the XML external entities, failing to start with an error like the following:

```
$ java -jar jenkins.war --realmClassName=winstone.realm.FileRealm --fileRealm.configFile=users.xml
[…]
[Fatal Error] :1:1: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
2022-02-10 16:50:32.904+0000 [id=1]     INFO    winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to setup authentication realm
        at winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        at winstone.HostGroup.initHost(HostGroup.java:66)
        at winstone.HostGroup.<init>(HostGroup.java:45)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:376)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:304)
        at Main.main(Main.java:108)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:69)
        ... 10 more
Caused by: winstone.WinstoneException: Error parsing the users XML document
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:124)
        at winstone.realm.FileRealm.<init>(FileRealm.java:58)
        ... 15 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:121)
        ... 16 more
2022-02-10 16:50:32.905+0000 [id=1]     SEVERE  winstone.Logger#logInternal: Container startup failed
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:121)
Caused: winstone.WinstoneException: Error parsing the users XML document
        at winstone.realm.FileRealm.parseStreamToXML(FileRealm.java:124)
        at winstone.realm.FileRealm.<init>(FileRealm.java:58)
Caused: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at winstone.HostConfiguration.<init>(HostConfiguration.java:69)
Caused: java.io.IOException: Failed to setup authentication realm
        at winstone.HostConfiguration.<init>(HostConfiguration.java:71)
        at winstone.HostGroup.initHost(HostGroup.java:66)
        at winstone.HostGroup.<init>(HostGroup.java:45)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:376)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:304)
        at Main.main(Main.java:108)
```

### Anything else?

There is no security issue here. For a user to be able to exploit this, they would have to be able to control the arguments to the Jenkins Java process, at which point they could just as easily take down service by e.g. passing in an invalid argument or giving themselves access to an administrative account.

I confirmed with the [Security Team](https://www.jenkins.io/security/) that this issue can be discussed in a public forum in [SECURITY-2609](https://issues.jenkins.io/browse/SECURITY-2609) prior to raising this issue.

Suggest the following patch:

```java
diff --git a/src/main/java/winstone/realm/FileRealm.java b/src/main/java/winstone/realm/FileRealm.java
index 64e1e14..b5b7904 100644
--- a/src/main/java/winstone/realm/FileRealm.java
+++ b/src/main/java/winstone/realm/FileRealm.java
@@ -16,6 +16,7 @@ import winstone.WinstoneException;
 import winstone.WinstoneResourceBundle;
 import winstone.cmdline.Option;
 
+import javax.xml.XMLConstants;
 import javax.xml.parsers.DocumentBuilder;
 import javax.xml.parsers.DocumentBuilderFactory;
 import java.io.File;
@@ -111,6 +112,9 @@ public class FileRealm extends HashLoginService {
         try {
             // Use JAXP to create a document builder
             DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
+            factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
+            factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
+            factory.setXIncludeAware(false);
             factory.setExpandEntityReferences(false);
             factory.setValidating(false);
             factory.setNamespaceAware(false);
```

### PR DESCRIPTION
**Pull request by Vlatombe**
Previous approach was not relevant as it didn't prevent introduction of new violations.

This fixes some of the existing violations or ignored them after analysis. For the remaining ones, they are now excluded (same as in `jenkins`) and new violations will be detected.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Fixes #208
Fixes #209

### CODE REVIEW

File: src/main/java/winstone/Launcher.java [hunk 1]
```diff
@@ -229,8 +224,11 @@ private void writePortToFileIfNeeded() throws IOException {
                     int port = ((ServerConnector) connector).getLocalPort();
                     Path portFile = Paths.get(portFileName);
                     Path portDir = portFile.getParent();
+                    if (portDir == null) {
+                        throw new IllegalArgumentException("Given port file name doesn't have a parent: " + portFileName);
+                    }
                     Files.createDirectories(portDir);
-                    Path tmpPath = Files.createTempFile(portDir, portFile.getFileName().toString(), null);
+                    Path tmpPath = Files.createTempFile(portDir, portFileName, null);
```
Comment (olamy) [inline src/main/java/winstone/Launcher.java:231]: this cause `java.lang.IllegalArgumentException: Invalid prefix or suffix` as now the full path (if the user provide a full absolute path such as the unit test) is used as prefix which is not not possible.
ignore this fake/false positive spotbugs as there are many checks on this just few lines before.

**Review by olamy — CHANGES_REQUESTED** [review]

File: src/main/java/winstone/Launcher.java [hunk 2]
```diff
@@ -228,7 +229,12 @@ private void writePortToFileIfNeeded() throws IOException {
                         throw new IllegalArgumentException("Given port file name doesn't have a parent: " + portFileName);
                     }
                     Files.createDirectories(portDir);
-                    Path tmpPath = Files.createTempFile(portDir, portFileName, null);
+                    Path fileName = portFile.getFileName();
+                    if (fileName == null) {
+                        // Should never happen, but spotbugs
```
Comment (olamy) [inline src/main/java/winstone/Launcher.java:234]: 🤣

**Review by olamy — APPROVED** [review]
