### PR TITLE
Delay shutdown of logging facilities until the application has completed its shutdown process

### LINKED ISSUE #219: Logging facilities not available during application shutdown process
### Jenkins and plugins versions report

Jenkins 2.343

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.4 LTS x86_64

### Reproduction steps

1. Download Jenkins 2.343 or later.
2. Run `java -jar war/target/jenkins.war`.
3. Press Control-C.

### Expected Results

The application shutdown process prints the following logs:

```
2022-04-12 16:55:59.703+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@6cd24612{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.session.HouseKeeper#stopScavenging: node0 Stopped scavenging
2022-04-12 16:55:59.711+0000 [id=26]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2022-04-12 16:55:59.714+0000 [id=26]    INFO    jenkins.model.Jenkins$16#onAttained: Started termination
2022-04-12 16:55:59.720+0000 [id=26]    INFO    jenkins.model.Jenkins$16#onAttained: Completed termination
2022-04-12 16:55:59.720+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2022-04-12 16:55:59.723+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2022-04-12 16:55:59.725+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2022-04-12 16:55:59.737+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2022-04-12 16:55:59.737+0000 [id=26]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
2022-04-12 16:55:59.738+0000 [id=26]    INFO    o.e.j.s.handler.ContextHandler#doStop: Stopped w.@652ab8d9{Jenkins v2.344-SNAPSHOT,/,null,STOPPED}{/home/basil/.jenkins/war}
```

### Actual Results

The application shutdown process does not print any logs:

```
2022-04-12 16:57:31.176+0000 [id=32]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2022-04-12 16:57:31.176+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
```

### Anything else?

As described in [JDK-8161253](https://bugs.openjdk.java.net/browse/JDK-8161253), there is no way to control the order of execution of shutdown hooks. When the `LogManager#Cleaner` shutdown hook runs before Winstone's shutdown hook, it shuts down logging facilities. Logging facilities are subsequently unavailable to the application shutdown process, which is invoked from Winstone's shutdown hook.

In the comments to JDK-8161253, Jason Mehrens suggests a workaround: creating a custom log handler and installing it on the root logger before all other log handlers. Since the first action of `LogManager#Cleaner` is to close all the installed log handlers on the root logger, it will invoke the custom log handler's `close()` method. At this point, the custom log handler has intercepted control and can delay shutdown of logging facilities until the application has completed its shutdown process.

The following patch implements this workaround:

```java
diff --git a/src/main/java/winstone/Launcher.java b/src/main/java/winstone/Launcher.java
index 843ec11..5522270 100644
--- a/src/main/java/winstone/Launcher.java
+++ b/src/main/java/winstone/Launcher.java
@@ -42,9 +42,11 @@ import java.nio.file.StandardOpenOption;
 import java.util.ArrayList;
 import java.util.List;
 import java.util.Map;
+import java.util.Objects;
 import java.util.logging.ConsoleHandler;
 import java.util.logging.Handler;
 import java.util.logging.Level;
+import java.util.logging.LogRecord;
 
 /**
  * Implements the main launcher daemon thread. This is the class that gets
@@ -74,12 +76,44 @@ public class Launcher implements Runnable {
 
     public final Server server;
 
+    private boolean shutdownComplete;
+
     /**
      * Constructor - initialises the web app, object pools, control port and the
      * available protocol listeners.
      */
     public Launcher(Map<String, String> args) throws IOException {
         boolean success=false;
+        /*
+         * As described in JDK-8161253, there is no way to control the order of execution of
+         * shutdown hooks. When LogManager#Cleaner runs before our custom shutdown hook, logging
+         * facilities are not available to the application shutdown process. In the comments to
+         * JDK-8161253, Jason Mehrens suggests a workaround: creating a custom log handler and
+         * installing it on the root logger before all other log handlers. Since the first action of
+         * LogManager#Cleaner is to close all the installed log handlers on the root logger, it will
+         * invoke the custom log handler's close() method. At this point, we have intercepted
+         * control and can delay shutdown of logging facilities until the application has completed
+         * its shutdown process.
+         *
+         * The installLogHandler() method implements the above workaround, which creates an
+         * obligation to notify the custom log handler, via the Launcher#shutdown() method, that the
+         * application shutdown process is complete and logging facilities may be shut down.
+         *
+         * - In the case of successful launch, we execute the finally portion of the try/finally
+         *   block below, which does not call Launcher#shutdown() in the success case, then we
+         *   install the shutdown hook, then when the user terminates the application the shutdown
+         *   hook shuts down the application, then the shutdown hook calls Launcher#shutdown(), then
+         *   finally the custom log handler is notified.
+         *
+         * - In the case of unsuccessful launch, we execute the finally portion of the try/finally
+         *   block below, which calls Launcher#shutdown() in the failure case, which then notifies
+         *   the custom log handler.
+         *
+         * In either case the obligation is fulfilled and the custom log handler is notified of
+         * application shutdown, at which point it proceeds to shut down logging facilities as the
+         * last action prior to process termination.
+         */
+        installLogHandler();
         try {
             Logger.log(Logger.MAX, RESOURCES, "Launcher.StartupArgs", args + "");
 
@@ -220,6 +254,60 @@ public class Launcher implements Runnable {
         Runtime.getRuntime().addShutdownHook(new ShutdownHook(this));
     }
 
+    private boolean isShutdownComplete() {
+        return shutdownComplete;
+    }
+
+    /**
+     * Install our custom log handler that waits for application shutdown to complete before
+     * running.
+     */
+    private void installLogHandler() {
+        java.util.logging.Logger root = java.util.logging.Logger.getLogger("");
+        /*
+         * By installing our custom log handler before all others, we ensure that logging facilities
+         * are available during the application shutdown process.
+         */
+        Handler[] handlers = root.getHandlers();
+        for (Handler h : handlers) {
+            root.removeHandler(h);
+        }
+        root.addHandler(new LogHandler(this));
+        for (Handler h : handlers) {
+            root.addHandler(h);
+        }
+    }
+
+    /**
+     * Custom log handler that waits for application shutdown to complete before running.
+     */
+    private static class LogHandler extends Handler {
+        private final Launcher launcher;
+
+        LogHandler(Launcher launcher) {
+            this.launcher = Objects.requireNonNull(launcher);
+        }
+
+        @Override
+        public void publish(LogRecord record) {}
+
+        @Override
+        public void flush() {}
+
+        @Override
+        public void close() {
+            try {
+                synchronized (launcher) {
+                    while (!launcher.isShutdownComplete()) {
+                        launcher.wait();
+                    }
+                }
+            } catch (InterruptedException e) {
+                Thread.currentThread().interrupt();
+            }
+        }
+    }
+
     private void writePortToFileIfNeeded() throws IOException {
         String portFileName = System.getProperty(WINSTONE_PORT_FILE_NAME_PROPERTY);
         if (portFileName != null) {
@@ -355,6 +443,10 @@ public class Launcher implements Runnable {
         } catch (Exception e) {
             Logger.log(Logger.INFO, RESOURCES, "Launcher.FailedShutdown", e);
         }
+        synchronized (this) {
+            shutdownComplete = true;
+            notifyAll();
+        }
 
         if (this.controlThread != null) {
             this.controlThread.interrupt();
```

### PR DESCRIPTION
**Pull request by basil**
Fixes #219.

### Steps to reproduce

1. Run `java -jar war/target/jenkins.war`.
2. Press Control-C.

### Expected results

**Note:** These are the _actual_ results with this PR.

The application shutdown process prints the following logs:

```
2022-04-12 16:55:59.703+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@6cd24612{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.session.HouseKeeper#stopScavenging: node0 Stopped scavenging
2022-04-12 16:55:59.711+0000 [id=26]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2022-04-12 16:55:59.714+0000 [id=26]    INFO    jenkins.model.Jenkins$16#onAttained: Started termination
2022-04-12 16:55:59.720+0000 [id=26]    INFO    jenkins.model.Jenkins$16#onAttained: Completed termination
2022-04-12 16:55:59.720+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpDisconnectComputers: Starting node disconnection
2022-04-12 16:55:59.723+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpShutdownPluginManager: Stopping plugin manager
2022-04-12 16:55:59.725+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpPersistQueue: Persisting build queue
2022-04-12 16:55:59.737+0000 [id=26]    INFO    jenkins.model.Jenkins#_cleanUpAwaitDisconnects: Waiting for node disconnection completion
2022-04-12 16:55:59.737+0000 [id=26]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
2022-04-12 16:55:59.738+0000 [id=26]    INFO    o.e.j.s.handler.ContextHandler#doStop: Stopped w.@652ab8d9{Jenkins v2.344-SNAPSHOT,/,null,STOPPED}{/home/basil/.jenkins/war}
```

### Actual results

The application shutdown process does not print any logs:

```
2022-04-12 16:57:31.176+0000 [id=32]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2022-04-12 16:57:31.176+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
```

### Evaluation

As described in [JDK-8161253](https://bugs.openjdk.java.net/browse/JDK-8161253), there is no way to control the order of execution of shutdown hooks. When the `LogManager#Cleaner` shutdown hook runs before Winstone's shutdown hook, it shuts down logging facilities. Logging facilities are subsequently unavailable to the application shutdown process, which is invoked from Winstone's shutdown hook.

### Solution

In the comments to JDK-8161253, Jason Mehrens suggests a workaround: create a custom log handler and install it on the root logger before all other log handlers. Since the first action of `LogManager#Cleaner` is to close all the installed log handlers on the root logger, it will invoke the custom log handler's `close()` method. At this point, the custom log handler has intercepted control and can delay shutdown of logging facilities until the application has completed its shutdown process.

### Implementation

Added a 5-second sleep to ensure that we don't wait forever if the shutdown process is not making progress.

### Testing disconnection

Ran the steps to reproduce before and after this change. Before this change, I could reproduce this problem. After this change, I could not.

Also ran this change against core with an artificial modification to add a 30-second sleep to the application shutdown process. Verified that we stopped getting logs after 5 seconds, ensuring that the timeout logic was working.

### CODE REVIEW

**Review by timja — APPROVED** [review]

File: src/main/java/winstone/Launcher.java [hunk 1]
```diff
@@ -65,6 +68,8 @@ public class Launcher implements Runnable {
 
     private int CONTROL_TIMEOUT = 2000; // wait 2s for control connection
 
+    private static int SHUTDOWN_TIMEOUT = 5000; // wait 5s for shutdown
```
Comment (jglick) [inline src/main/java/winstone/Launcher.java:71]: With a lot of plugins running `@Terminator`s, 5s might be tight. I would suggest 10–20s as a more typical shutdown grace period for Jenkins.

**Review by jglick — APPROVED** [review]
Seems to work even with https://github.com/jenkinsci/log-cli-plugin/pull/119 active.

File: src/main/java/winstone/Launcher.java (hunk 1 above)
Comment (basil) [reply src/main/java/winstone/Launcher.java:71]: I'll change it to 20 seconds
